CREATE TABLE IF NOT EXISTS Systems (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Objects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    system_id INTEGER NOT NULL,
    FOREIGN KEY (system_id) REFERENCES Systems(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ACTIONS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    system_id INTEGER NOT NULL,
    object_id INTEGER,
    FOREIGN KEY (system_id) REFERENCES Systems(id) ON DELETE CASCADE
    FOREIGN KEY (object_id) REFERENCES Objects(id) ON DELETE CASCADE
);